### PR TITLE
Some Refactoring of growforest

### PR DESCRIPTION
**Pull request by barnjamin**
Refactoring a bit to make the main function of growforest.go smaller and more readable to me.  Still more that can be done but I wont bother you with PRs if you prefer the current format.

Please check this over and run against any known data. Builds fine but I don't have testable data available.

### CODE REVIEW

**Comment by barnjamin** [comment]
Even if this passes, dont merge just yet.  Testing accuracy with the benchmarks script it looks like this lost some accuracy.  Trying to track it down now.

**Comment by barnjamin** [comment]
on par with existing one now after 92c9c6c

**Comment by ryanbressler** [comment]
Sorry I missed this, I was on vacation. Are you still interested in landing it?

**Comment by barnjamin** [comment]
No sweat, I ended up writing my own RF implementation. Only merge if you
want this as is.

**Pull request closed without merging**
